django_celery/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import RedirectView

admin.autodiscover()

urlpatterns = patterns('',

    url(r'^admin/', include(admin.site.urls)),
)

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'django_celery.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    (r'^file_process/', include('file_process.urls')),
    (r'^$', RedirectView.as_view(url='/file_process/list/')), # Just for ease of use.
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

file_process/urls.py
# -*- coding: utf-8 -*-
"""URLs for genome reports and variant information"""
from django.conf.urls import patterns, url

from .views import GenomeImportView

from .views import receive_23andme, complete_23andme, commentary

urlpatterns = patterns(
    '',
    url(r'^genome_import/?$', GenomeImportView.as_view(),
        name='genome_import'),
    url(r'^commentary/(?P<variant_id>\d+)/$', commentary, name='commentary'),
    url(r'^receive_23andme/?', receive_23andme, name='receive_23andme'),
    url(r'^complete_23andme/?', complete_23andme, name='complete_23andme')
)

genevieve/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView

admin.autodiscover()

urlpatterns = patterns(
    '',
    
    url(r'^contact-us/$',
        TemplateView.as_view(template_name='pages/contact_us.html'),
        name='contact_us'),

    url(r'^$', TemplateView.as_view(template_name='home.html')),

    url(r'^admin/', include(admin.site.urls)),

    url(r'^file_process/', include('file_process.urls',
                                   namespace='file_process')),
    url(r'^genomes/', include('genomes.urls',
                              namespace='genomes')),

    url(r'^account/', include('account.urls')),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

genomes/urls.py
# -*- coding: utf-8 -*-
"""URLs for genome reports and variant information"""
from django.conf.urls import patterns, url

from .views import (GenomeAnalysesView, GenomeReportView,
                    GenomeReportJSONView, ReportsJSON)

urlpatterns = patterns(
    '',
    url(r'^$', GenomeAnalysesView.as_view(), name='reports_list'),
    url(r'^report/(?P<pk>\d+)/$', GenomeReportView.as_view(),
        name='report'),
    url(r'^report/(?P<pk>\d+)/json$', GenomeReportJSONView.as_view(),
        name='report-json'),
    url(r'get-reports/$', ReportsJSON.as_view(), name='get-reports'),
)

genevieve/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.shortcuts import render_to_response
from django.http import HttpResponseRedirect
from django.views.generic.edit import CreateView


def home(request):
    return render_to_response('home.html')


def auto_login(request):
    if request.user.is_authenticated():
        return HttpResponseRedirect('/file_process')


class UserCreateView(CreateView):
    """
    A view that creates a new user, logs them in, and redirects them to the
    root URL.
    """
    model = User
    form_class = UserCreationForm
    template_name = 'signup.html'

    def form_valid(self, form):
        form.save()

        user = authenticate(username=form.cleaned_data.get('username'),
                            password=form.cleaned_data.get('password1'))

        if user is not None:
            login(self.request, user)

        return HttpResponseRedirect('/')

genevieve/templates/pages/about.html
{% extends 'base.html' %}

{% load static from staticfiles %}

{% block main %}
<ul class="nav nav-pills below-navbar">
  <li class="active">
    <a data-toggle="pill" href="#project">About Genevieve</a>
  </li>

  <li><a href="#team" data-toggle="pill">Our Team</a></li>
</ul>

<div class="tab-content">

  <div class="tab-pane active" id="project">

    <div class="row">
      <div class="col-lg-12">
        <h2 class="page-header">About Genevieve</h2>
      </div>

    </div>
  </div>

  <div class="tab-pane" id="team">
    <div class="row">
      <div class="col-lg-12">
        <h2 class="page-header">Our team</h2>
      </div>
    </div> <!-- row -->
  </div> <!-- tab-pane -->
  {% endblock %}

genevieve/templates/pages/community_guidelines.html
{% extends 'base.html' %}

{% block main %}
<ul class="nav nav-pills below-navbar">
  <li class="active"><a data-toggle="pill" href="#about">
    About our guidelines</a></li>
  <li><a href="#public-data-use" data-toggle="pill">
    Public Data Use guidelines</a></li>
  <li><a href="#username" data-toggle="pill">Username guidelines</a></li>
</ul>

<div class="tab-content">
  <div class="tab-pane active" id="about">
    <h1>Community Guidelines</h1>
 </div>
</div>
{% endblock main %}

genevieve/templates/pages/contact_us.html
{% extends 'base.html' %}

{% block main %}
  <h1>Contact us</h1>

  <p>For questions please contact us at
    <a href="mailto:genevieve-support@personalgenomes.org">
      genevieve-support@personalgenomes.org</a>.
  </p>
{% endblock %}

genevieve/templates/pages/home.html
{% extends "base.html" %}

{% block content %}
<div class="container">
  {% block main %}
  <div class="text-center">
    <h1> Welcome to Genevieve </h1>
    {% if user.is_anonymous %}
    <div id="signup-button">
      <a href="/accounts/signup/">
        <button type="button" class="btn btn-success btn-lg">
          Sign Up</button>
      </a>
    </div>
    {% else %}
    <a href="{% url 'genomes:reports_list' %}"><button type="button"
        class="btn btn-success btn-lg">
      Go to genome reports</button></a>
    <a href="{% url 'file_process:genome_import' %}"><button type="button"
        class="btn btn-success btn-lg">
      Import a genome</button></a>
    {% endif %}
  </div>
  {% endblock main %}
</div>

{% endblock %}