django_celery/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import RedirectView

admin.autodiscover()

urlpatterns = patterns('',

    url(r'^admin/', include(admin.site.urls)),
)

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'django_celery.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    (r'^file_process/', include('file_process.urls')),
    (r'^$', RedirectView.as_view(url='/file_process/list/')), # Just for ease of use.
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

file_process/urls.py
# -*- coding: utf-8 -*-
"""URLs for genome reports and variant information"""
from django.conf.urls import patterns, url

from .views import GenomeImportView

from .views import receive_23andme, complete_23andme, commentary

urlpatterns = patterns(
    '',
    url(r'^genome_import/?$', GenomeImportView.as_view(),
        name='genome_import'),
    url(r'^commentary/(?P<variant_id>\d+)/$', commentary, name='commentary'),
    url(r'^receive_23andme/?', receive_23andme, name='receive_23andme'),
    url(r'^complete_23andme/?', complete_23andme, name='complete_23andme')
)

genevieve/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView

admin.autodiscover()

urlpatterns = patterns(
    '',
    
    url(r'^contact-us/$',
        TemplateView.as_view(template_name='pages/contact_us.html'),
        name='contact_us'),

    url(r'^$', TemplateView.as_view(template_name='home.html')),

    url(r'^admin/', include(admin.site.urls)),

    url(r'^file_process/', include('file_process.urls',
                                   namespace='file_process')),
    url(r'^genomes/', include('genomes.urls',
                              namespace='genomes')),

    url(r'^account/', include('account.urls')),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

genomes/urls.py
# -*- coding: utf-8 -*-
"""URLs for genome reports and variant information"""
from django.conf.urls import patterns, url

from .views import (GenomeAnalysesView, GenomeReportView,
                    GenomeReportJSONView, ReportsJSON)

urlpatterns = patterns(
    '',
    url(r'^$', GenomeAnalysesView.as_view(), name='reports_list'),
    url(r'^report/(?P<pk>\d+)/$', GenomeReportView.as_view(),
        name='report'),
    url(r'^report/(?P<pk>\d+)/json$', GenomeReportJSONView.as_view(),
        name='report-json'),
    url(r'get-reports/$', ReportsJSON.as_view(), name='get-reports'),
)

file_process/models.py
from django.db import models

# Define models here

file_process/forms.py
from django import forms
from django.conf import settings


class GenomeUploadForm(forms.Form):
    """File upload form."""
    uploadfile = forms.FileField(
        label='Select a file'
    )
    reportname = forms.CharField()
    genome_format = forms.ChoiceField(
        [('vcf', 'VCF'), ('cgivar', 'Complete Genomics var file')])

    # Must be gzipped and under Max_Upload_Size
    def clean_uploadfile(self):
        content = self.cleaned_data['uploadfile']
        print "Content Size =",
        print content.size
        if content.size > int(settings.MAX_UPLOAD_SIZE):
            raise forms.ValidationError('Your file was too large.')
        #if not content.name.endswith('.gz'):
        #    raise forms.ValidationError('Are you sure you uploaded a gzipped VCF file?')
        return content

    def file_name(self):
        report = self.cleaned_data['reportname']
        print report
        if not report:
            raise forms.ValidationError('Please name your file.')

file_process/views.py
# -*- coding: utf-8 -*-
"""Views for genome reports and genetic variants"""

import requests

from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.http import Http404, HttpResponse, HttpResponseRedirect
from django.views.generic.edit import FormView
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.utils.decorators import method_decorator

from genomes.models import GenomeAnalysis
from variants.models import ClinVarRecord

from .forms import GenomeUploadForm
from .tasks import read_input_genome, analyze_23andme_from_api


def make_auth_23andme_url():
    return ("https://api.23andme.com/authorize/?" +
            "&".join(["response_type=code",
                      "client_id=%s" % settings.CLIENT_ID_23ANDME,
                      "scope=%s" % "basic names genomes"]))


def complete_23andme_auth(code):
    parameters = {
        'client_id': settings.CLIENT_ID_23ANDME,
        'client_secret': settings.CLIENT_SECRET_23ANDME,
        'grant_type': 'authorization_code',
        'code': code,
        'redirect_uri': settings.REDIRECT_URI,
        'scope': 'basic names genomes'
    }
    token_req = requests.post("https://api.23andme.com/token/",
                              data=parameters, verify=False)
    if token_req.status_code == 200 and 'access_token' in token_req.json():
        access_token = token_req.json()['access_token']
        headers = {'Authorization': 'Bearer %s' % access_token}
        names_req = requests.get("https://api.23andme.com/1/names/",
                                 headers=headers, verify=False)
        if names_req.status_code == 200:
            return names_req.json(), access_token
    return None, None


def receive_23andme(request):
    """Receive 23andme authorization, prompt selection of account data."""
    data, access_token = complete_23andme_auth(request.GET['code'])
    if data and access_token:
        request.session['23andme_access_token'] = access_token
        return render_to_response('file_process/select_23andme.html',
                                  {'profiles': data['profiles']},
                                  context_instance=RequestContext(request))
    else:
        return HttpResponse("Sorry, unable to retrieve token!")


def complete_23andme(request):
    """Initiate 23andme import and processing and redirect to reports list"""
    if request.method == 'POST':
        if 'profile_id' in request.POST:
            print "Sending to analyze_23andme_from_api"
            analyze_23andme_from_api.delay(
                request.session['23andme_access_token'],
                request.POST['profile_id'], request.user)
            return HttpResponseRedirect(
                reverse('genomes:reports_list'))
        else:
            return HttpResponse("Sorry that didn't seem to work")


class GenomeImportView(FormView):
    form_class = GenomeUploadForm
    success_url = '/genomes/'
    template_name = 'file_process/genome_import.html'

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(GenomeImportView, self).dispatch(*args, **kwargs)

    def form_valid(self, form):
        form.user = self.request.user
        new_analysis = GenomeAnalysis(
            uploadfile=self.request.FILES['uploadfile'],
            user=form.user, name=self.request.POST['reportname'])
        genome_format = self.request.POST['genome_format']
        new_analysis.save()
        read_input_genome.delay(analysis_in=new_analysis,
                                genome_format=genome_format)
        return super(GenomeImportView, self).form_valid(form)

    def get_context_data(self, **kwargs):
            context = super(GenomeImportView, self).get_context_data(**kwargs)
            additional_context = {
                'auth_23andme_url': make_auth_23andme_url(),
            }
            context.update(additional_context)
            return context


def commentary(request, variant_id):
    """Genevieve comments on a specific genetic variant"""
    # Authenticate
    if not request.user.is_authenticated():
        return render_to_response('file_process/login_error.html')
    try:
        specific_variant = ClinVarRecord.objects.get(pk=variant_id)
        return render_to_response(
            'file_process/community_comments.html',
            {'variant_id': variant_id,
             'specific_variant': specific_variant}
            )
    except ClinVarRecord.DoesNotExist:
        raise Http404

file_process/templates/file_process/community_comments.html
{% extends "base.html" %}
{% block title %}Community Comments{% endblock %}
{% block head %}
<link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet">
<script src="http://code.jquery.com/jquery-2.0.3.min.js"></script>
<script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
<link href="//cdnjs.cloudflare.com/ajax/libs/x-editable/1.5.0/bootstrap3-editable/css/bootstrap-editable.css" rel="stylesheet"/>
<script src="//cdnjs.cloudflare.com/ajax/libs/x-editable/1.5.0/bootstrap3-editable/js/bootstrap-editable.min.js"></script>
<script>
$.fn.editable.defaults.mode = 'inline';
$(document).ready(function() {
    $('#username').editable();
});
</script>
{% endblock %}
{% block navbar %}
<a href="/file_process/"><button type="button" class="btn btn-default navbar-btn">Genome Uploads</button></a>
<a href="{% url 'account_logout' %}"><button type="button" class="btn btn-primary navbar-btn navbar-right">Logout</button></a>
{% endblock %}
{% block content %}
<h2>
<a href="http://www.ncbi.nlm.nih.gov/clinvar/{{specific_variant.accnum}}">
{{specific_variant.accnum}}</a></h2>
<h3>{{specific_variant.condition}}</h3>
<p><a href="#" id="username" data-type="text" data-pk="1" data-url="/post" data-title="Variant Commentary">Comments</a></p>
{% endblock %}

file_process/templates/file_process/genome_import.html
{% extends "home.html" %}
{% block title %}Genevieve {{username}}'s Reports{% endblock %}
{% block navbar %}
<a href="{% url 'account_logout' %}"><button type="button"
    class="btn btn-primary navbar-btn navbar-right">
  Logout</button></a>
{% endblock %}

{% block main %}

<p>Import data from 23andme:</p>

<div style="margin-top:10px; margin-bottom:20px;">
  <a class='btn btn-primary' href='{{auth_23andme_url}}'>
    Import genotyping data from 23andme
  </a>
</div>

<p>Or upload a file:</p>

<form role="form" action="{% url 'file_process:genome_import' %}" method="post"
    enctype="multipart/form-data">
  {% csrf_token %}
  <div class="form-group">
    {% if form.uploadfile.errors %}
    <div class="alert alert-danger" role="alert">
      {{ form.uploadfile.errors }}
    </div>
    {% endif %}
    <input type="file" id="id_uploadfile"  name="uploadfile">
    <p class="help-block">
      Please upload a gzipped vcf file
    </p>
  </div>
  <div class="form-group">
    {% if form.reportname.errors %}
    <div class="alert alert-danger" role="alert">
      {{ form.reportname.errors }}
    </div>
    {% endif %}
    <input type="text" id="id_reportname" class="form-control"
      name="reportname" type="text" placeholder="Enter Filename">
  </div>
  <div class="form-group">
    <select id="id_genome_format" name="genome_format">
      <option value="vcf">VCF</option>
      <option value="cgivar">Complete Genomics var file</option>
    </select>
  </div>
  <p>
    <button type="submit" class="btn btn-default">Submit</button>
  </p>
</form>

{% endblock main %}

file_process/templates/file_process/genomeanalysis_list.html
{% extends "home.html" %}
{% block title %}Genevieve {{ username }}'s Reports{% endblock %}

{% block main %}
{# Welcome user #}
<h3>Welcome {{ request.user.username }}!</h3>

{# List genome analyses #}
{% if genomeanalysis_list %}
<table class="table table-striped">
  <thead>
    <tr>
      <th>File Name</th>
      <th>Date Added</th>
      <th>Uploaded File</th>
       <th>Processed File</th>
       <th>Report</th>
     </tr>
  </thead>
  <tbody>
    {% for genomeanalysis in genomeanalysis_list %}
    <tr>
      <td>{{ genomeanalysis.name }}</td>
      <td>{{ genomeanalysis.timestamp }}</td>
      <td>
        <a href="{{ genomeanalysis.uploadfile.url }}">
          Download Uploaded File</a>
      </td>
      <td>
        {% if genomeanalysis.processedfile %}
        <a href="{{ genomeanalysis.processedfile.url }}">
          Download Processed File</a>
        {% else %}
        File processing not complete.
        {% endif %}
      </td>
      <td>
        {% if genomeanalysis.variants %}
        <a href="report/{{ genomeanalysis.id }}/">View Report</a>
        {% endif %}
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% else %}
<p>No files uploaded.</p>
{% endif %}

{# 23andme import #}
<div style="margin-top:10px; margin-bottom:20px;">
  <a class='btn btn-primary' href='{{auth_23andme_url}}'>
    Import genotyping data from 23andme
  </a>
</div>

<p>
  Or use the form below to import a genome file...
</p>

{# Abstract so we can load same form on a different URL in event of errors. #}
{% include 'file_process/genome-import-form.html' %}

{% endblock main %}

file_process/templates/file_process/login_error.html
{% extends "base.html" %}
{% block content %}
Sorry!  You're not currently logged in.
<a href="/"><button type="button" class="btn btn-primary">Please Login First</button></a>
{% endblock %}

file_process/templates/file_process/not_authorized.html
{% extends "base.html" %}
{% block content %}
Sorry!  You're not authorized to view this report.
<a href="/file_process/"><button type="button" class="btn btn-primary">Go Back to File Reports</button></a>
{% endblock %}

file_process/templates/file_process/select_23andme.html
{% extends "base.html" %}

{% block title %}Genevieve: Confirm 23andme import for {{username}}{% endblock title%}

{% block content %}
    <h3>Please select and confirm 23andme genotyping data import</h3>

    <form role="form" action="{% url 'file_process:complete_23andme' %}" method="post">
    {% csrf_token %}
        {% for profile in profiles %}
        <input type="radio" name="profile_id"
          value="{{ profile.id }}">{{ profile.first_name }} {{ profile.last_name }}</input>
        {% endfor %}
      <p><button type="submit"
          class="btn btn-default">Import genome</button></p>
    </form>

    <a class="btn" href="{% url 'genomes:reports_list' %}">Cancel</a>
{% endblock %}